Sprint7
ClevertecFrontendLab/alexeyvalko pull request #5
Opened 2023-03-25 18:10 UTC by alexeyvalko

2023-03-25 18:21 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 97%.
Общее количество тестов: 98.
Количество непройденных тестов: 2.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679768513/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679768513/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679768513/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679768513/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679768513/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679768513/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679768513/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679768513/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679768513/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679768513/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679768513/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679768513/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679768513/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679768513/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679768513/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679768513/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679768513/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679768513/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679768513/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679768513/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679768513/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679768513/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679768513/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679768513/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679768513/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679768513/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679768513/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679768513/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679768513/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679768513/9-app%20-burger-menu-close-768px.png)
***
**Sprint 5 -- authorization and registartion -- authorization -- redirect authorization (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679768513/Sprint%205%20--%20authorization%20and%20registartion%20--%20authorization%20--%20redirect%20authorization%20(failed).png)
***
**Sprint 5 -- authorization and registartion -- authorization -- success authorization (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679768513/Sprint%205%20--%20authorization%20and%20registartion%20--%20authorization%20--%20success%20authorization%20(failed).png)

2023-03-25 20:37 UTC, SergeyGlazun requested changes

2023-03-25 20:37 UTC, SergeyGlazun commented on src/components/profile/profile-booking/profile-booking.tsx
> +  const handleClickDeleteBooking = async () => {
в компонент вам должны придти просто данные не нужно тут делать логику получения данных, обработки ошибок

2023-03-25 20:37 UTC, SergeyGlazun commented on cypress.config.ts
>  export default defineConfig({
![image](https://user-images.githubusercontent.com/70904466/227739887-a8c814a6-e3cf-4bcf-9e37-a3262b90a8c6.png)
проверти отправку отценок, каждый раз выскакивает ошибка

2023-03-25 20:37 UTC, SergeyGlazun commented on cypress.config.ts
>  export default defineConfig({
![image](https://user-images.githubusercontent.com/70904466/227739920-8e0f9e58-1ac5-4166-a11e-711ba482bd14.png)

2023-03-25 21:34 UTC, ValadzkoAliaksei commented on src/components/books-list/books-list.tsx
> +                  type={CARD.VERTICAL}
то есть это тот же самый, продуктКард, меняется только type и ты зачем-то 2 раза его кидаешь?) хмммм....

2023-03-25 21:34 UTC, ValadzkoAliaksei commented on src/components/comments/comments.tsx
> +            .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
какие-то сложные вычисления.... можно в утилитку куда-нибудь вынести?

2023-03-25 21:34 UTC, ValadzkoAliaksei commented on src/store/app-slice.ts
>  const initialState: AppState = {
все интерфейсы переводи в типы, и избавься от I впереди

2023-03-25 21:34 UTC, ValadzkoAliaksei commented on src/store/error-logger.ts
> +      //   const errorMessage = action.payload?.data?.error?.message;
чистим

2023-03-26 13:57 UTC, alexeyvalko commented on src/store/error-logger.ts
> +      //   const errorMessage = action.payload?.data?.error?.message;
удалил

2023-03-26 13:57 UTC, alexeyvalko commented on src/store/app-slice.ts
>  const initialState: AppState = {
перевёл всё на типы

2023-03-26 13:58 UTC, alexeyvalko commented on src/components/comments/comments.tsx
> +            .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
вынес сортировку в хук useComments

2023-03-26 13:59 UTC, alexeyvalko commented on src/components/books-list/books-list.tsx
> +                  type={CARD.VERTICAL}
теперь карточка одна, меняется только её тип

2023-03-26 13:59 UTC, alexeyvalko commented on cypress.config.ts
>  export default defineConfig({
исправил

2023-03-26 14:00 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 98.
Количество непройденных тестов: 0.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679839199/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679839199/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679839199/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679839199/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679839199/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679839199/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679839199/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679839199/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679839199/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679839199/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679839199/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679839199/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679839199/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679839199/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679839199/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679839199/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679839199/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679839199/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679839199/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679839199/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679839199/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679839199/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679839199/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679839199/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679839199/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679839199/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679839199/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679839199/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679839199/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679839199/9-app%20-burger-menu-close-768px.png)

2023-03-26 14:41 UTC, SergeyGlazun requested changes

2023-03-26 14:41 UTC, SergeyGlazun commented on src/components/books-list/books-list.tsx
>    const { data: categories } = useGetCategoriesQuery();
![image](https://user-images.githubusercontent.com/70904466/227782258-f6391d66-93d4-41fc-a6d9-fc7c3c15df72.png)
после отправки сообшения обновление проиходит с задержкой

2023-03-26 14:41 UTC, SergeyGlazun commented on src/components/books-list/books-list.tsx
>    const [isFullSearch, setIsFullSearch] = useState(false);
![image](https://user-images.githubusercontent.com/70904466/227783032-4b27d905-c0eb-4ca2-ac29-2e69962090bf.png)
всего этого в компоненте не должно быть только получение готовых данных

2023-03-26 17:57 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 98.
Количество непройденных тестов: 0.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679853471/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679853471/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679853471/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679853471/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679853471/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679853471/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679853471/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679853471/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679853471/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679853471/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679853471/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679853471/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679853471/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679853471/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679853471/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679853471/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679853471/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679853471/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679853471/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679853471/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679853471/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679853471/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679853471/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679853471/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679853471/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679853471/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679853471/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679853471/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679853471/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679853471/9-app%20-burger-menu-close-768px.png)

2023-03-26 17:58 UTC, alexeyvalko commented on src/components/books-list/books-list.tsx
>    const [isFullSearch, setIsFullSearch] = useState(false);
вынес всю логику работы с api из компонентов

2023-03-26 17:58 UTC, alexeyvalko commented on src/components/books-list/books-list.tsx
>    const { data: categories } = useGetCategoriesQuery();
исправил

2023-03-26 18:21 UTC, SergeyGlazun approved these changes

2023-03-26 20:56 UTC, ValadzkoAliaksei commented on src/components/books-list/books-list.tsx
> +              <ProductCard
![image](https://user-images.githubusercontent.com/61273546/227803720-3eedf20f-8897-445f-8615-ab25062f5a11.png)
переход должен быть на all, а не на их категорию.

2023-03-26 20:56 UTC, ValadzkoAliaksei commented on src/components/books-list/books-list.tsx
> +                type={cardType}
![image](https://user-images.githubusercontent.com/61273546/227803774-34f44ebc-ab2e-4da6-858d-edd01127e19f.png)
если аватарки нет, то должен быть котик

2023-03-26 20:56 UTC, ValadzkoAliaksei commented on src/components/books-list/books-list.tsx
> +                    availableDate={book.delivery?.dateHandedTo || null}
![image](https://user-images.githubusercontent.com/61273546/227803909-43ae1915-81cf-4de6-81d2-4283dfd1b6c6.png)
нельзя выбирать при изменении брони тот же самый день, иначе запрос падает

2023-03-26 20:56 UTC, ValadzkoAliaksei commented on src/components/books-list/books-list.tsx
> +                    size={SIZE.SMALL}
![image](https://user-images.githubusercontent.com/61273546/227803969-3e845f20-7858-40f2-ae10-e54de0f6e59a.png)
Что-то с лоадарми, книга еще грузиться а лоадора нет и отображается не актуальная информация

2023-03-26 22:46 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 98%.
Общее количество тестов: 98.
Количество непройденных тестов: 1.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679870801/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679870801/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679870801/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679870801/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679870801/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679870801/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679870801/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679870801/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679870801/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679870801/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679870801/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679870801/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679870801/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679870801/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679870801/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679870801/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679870801/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679870801/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679870801/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679870801/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679870801/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679870801/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679870801/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679870801/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679870801/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679870801/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679870801/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679870801/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679870801/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679870801/9-app%20-burger-menu-close-768px.png)
***
**Sprint 6 -- booking and book rate -- booking edit modal -- check edit booking request success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexeyvalko/1679870801/Sprint%206%20--%20booking%20and%20book%20rate%20--%20booking%20edit%20modal%20--%20check%20edit%20booking%20request%20success%20(failed).png)

2023-03-26 23:02 UTC, ValadzkoAliaksei approved these changes

2023-03-27 06:43 UTC, merged